INSERT INTO educational_institution (name)
VALUES ('Pontifícia Universidade Católica de Minas Gerais - PUC Minas'),
       ('Universidade Federal de Minas Gerais - UFMG'),
       ('Centro Universitário de Belo Horizonte - UniBH'),
       ('Faculdade Pitágoras de Belo Horizonte'),
       ('Centro Universitário Newton Paiva'),
       ('Faculdade de Ciências Médicas de Minas Gerais'),
       ('Faculdade Promove de Belo Horizonte'),
       ('Universidade FUMEC'),
       ('Escola Superior Dom Helder Câmara'),
       ('Faculdade Senac Minas');


INSERT INTO course (name)
VALUES ('Administração'),
       ('Arquitetura e Urbanismo'),
       ('Biologia'),
       ('Biomedicina'),
       ('Ciência da Computação'),
       ('Ciência de Dados e Inteligência Artificial'),
       ('Ciências Biológicas'),
       ('Ciências Contábeis'),
       ('Ciências Econômicas'),
       ('Ciências Sociais'),
       ('Cinema e Audiovisual'),
       ('Direito'),
       ('Educação Física'),
       ('Engenharia Aeronáutica'),
       ('Engenharia Civil'),
       ('Engenharia de Computação'),
       ('Engenharia de Controle e Automação'),
       ('Engenharia de Energia'),
       ('Engenharia de Produção'),
       ('Engenharia de Software'),
       ('Engenharia Elétrica'),
       ('Engenharia Eletrônica e de Telecomunicação'),
       ('Engenharia Mecânica'),
       ('Engenharia Mecatrônica'),
       ('Engenharia Metalúrgica'),
       ('Engenharia Química'),
       ('Enfermagem'),
       ('Farmácia'),
       ('Filosofia'),
       ('Física'),
       ('Fisioterapia'),
       ('Fonoaudiologia'),
       ('Geografia'),
       ('História'),
       ('Jogos Digitais'),
       ('Jornalismo'),
       ('Letras'),
       ('Marketing'),
       ('Matemática'),
       ('Medicina'),
       ('Medicina Veterinária'),
       ('Nutrição'),
       ('Odontologia'),
       ('Pedagogia'),
       ('Psicologia'),
       ('Publicidade e Propaganda'),
       ('Relações Internacionais'),
       ('Relações Públicas'),
       ('Serviço Social'),
       ('Sistemas de Informação'),
       ('Tecnologia em Análise e Desenvolvimento de Sistemas'),
       ('Tecnologia em Banco de Dados'),
       ('Tecnologia em Comércio Exterior'),
       ('Tecnologia em Construção de Edifícios'),
       ('Tecnologia em Gestão Comercial'),
       ('Tecnologia em Gestão da Produção Industrial'),
       ('Tecnologia em Gestão de Recursos Humanos'),
       ('Tecnologia em Gestão Financeira'),
       ('Tecnologia em Gestão Pública'),
       ('Tecnologia em Gestão de Tecnologia da Informação'),
       ('Tecnologia em Jogos Digitais'),
       ('Tecnologia em Logística'),
       ('Tecnologia em Processos Gerenciais'),
       ('Tecnologia em Processos Metalúrgicos'),
       ('Tecnologia em Produção Audiovisual'),
       ('Tecnologia em Redes de Computadores'),
       ('Tecnologia em Segurança da Informação'),
       ('Teologia');

INSERT INTO student (name, email, cpf, rg, educational_institution_id, course_id, balance, password)
VALUES ('Lucas Almeida', 'aluno@exemplo.com', '12345678901', 'MG1234567', 1, 5, 1000, 'default'),
       ('Ana Beatriz Souza', 'ana.souza@exemplo.com', '23456789012', 'MG2345678', 2, 12, 2000, 'default'),
       ('Pedro Henrique Santos', 'pedro.santos@exemplo.com', '34567890123', 'MG3456789', 3, 20, 0, 'default'),
       ('Mariana Oliveira', 'mariana.oliveira@exemplo.com', '45678901234', 'MG4567890', 1, 14, 0, 'default'),
       ('Gabriel Ferreira', 'gabriel.ferreira@exemplo.com', '56789012345', 'MG5678901', 4, 22, 0, 'default'),
       ('Julia Pereira', 'julia.pereira@exemplo.com', '67890123456', 'MG6789012', 5, 28, 0, 'default'),
       ('Rafael Costa', 'rafael.costa@exemplo.com', '78901234567', 'MG7890123', 6, 35, 0, 'default'),
       ('Isabela Rodrigues', 'isabela.rodrigues@exemplo.com', '89012345678', 'MG8901234', 2, 43, 0, 'default'),
       ('Bruno Martins', 'bruno.martins@exemplo.com', '90123456789', 'MG9012345', 3, 18, 0, 'default'),
       ('Larissa Silva', 'larissa.silva@exemplo.com', '01234567890', 'MG0123456', 1, 27, 0, 'default'),
       ('Mateus Lima', 'mateus.lima@exemplo.com', '10234567891', 'MG1023456', 4, 10, 0, 'default'),
       ('Camila Rocha', 'camila.rocha@exemplo.com', '11234567892', 'MG1123456', 5, 50, 0, 'default'),
       ('Felipe Nunes', 'felipe.nunes@exemplo.com', '12234567893', 'MG1223456', 6, 3, 0, 'default'),
       ('Aline Cardoso', 'aline.cardoso@exemplo.com', '13234567894', 'MG1323456', 2, 38, 0, 'default'),
       ('Rodrigo Barros', 'rodrigo.barros@exemplo.com', '14234567895', 'MG1423456', 3, 19, 0, 'default'),
       ('Patricia Mendes', 'patricia.mendes@exemplo.com', '15234567896', 'MG1523456', 1, 6, 0, 'default'),
       ('Tiago Freitas', 'tiago.freitas@exemplo.com', '16234567897', 'MG1623456', 4, 45, 0, 'default'),
       ('Vanessa Ribeiro', 'vanessa.ribeiro@exemplo.com', '17234567898', 'MG1723456', 5, 61, 0, 'default'),
       ('Diego Araujo', 'diego.araujo@exemplo.com', '18234567899', 'MG1823456', 6, 8, 0, 'default'),
       ('Fernanda Costa', 'fernanda.costa@exemplo.com', '19234567890', 'MG1923456', 2, 32, 0, 'default');